services:
  chat-service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHATDB_URL=${CHATDB_URL}
      - LOCATION_SERVICE_GRPC_URL=${LOCATION_SERVICE_GRPC_URL}