version: '3.8'

services:
  chat-server:
    container_name: chat_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHATDB_URL=${CHATDB_URL}
      - LOCATION_SERVICE_GRPC_URL=${LOCATION_SERVICE_GRPC_URL}